INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Jada","Wooten","erat.neque.non@atiaculisquis.net","ISH76QVR3SQ"),("Amity","Melton","mi@pulvinar.net","BTW71JEZ5MT"),("Jamalia","Rios","arcu.ac.orci@sodaleselit.edu","RHQ48MNN8HS"),("Ima","Mcgowan","turpis.vitae@Pellentesquehabitantmorbi.org","RKG49WNX6HR"),("Perry","Sawyer","non@liberoProinmi.edu","PQC45MNV8AB"),("Sharon","Christian","netus.et.malesuada@consequat.co.uk","MRE41TUS7PO"),("Jada","Sims","habitant@acnullaIn.net","ABC39ZHG0JO"),("Pearl","Goodman","torquent@lorem.edu","JFS67SWW5PO"),("Hakeem","Crane","natoque.penatibus@Uttincidunt.co.uk","YEL69FCV2AE"),("Kaseem","Knox","aptent.taciti.sociosqu@elementum.ca","QET39EIH9RA");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Burton","Brewer","dui.Suspendisse.ac@senectus.co.uk","TYW19FUD1ST"),("Sean","Gutierrez","Proin@ridiculusmusProin.com","QXD82WVI8LR"),("Jack","Thornton","taciti.sociosqu@vitaemauris.edu","EGU18LHP4PK"),("Veronica","Joyner","Fusce@musAeneaneget.net","DRL11KGW2OO"),("April","Ashley","et@sem.ca","LHP49SXF1BW"),("Althea","Wooten","interdum.libero@lobortisquis.ca","AQI30UFP5DV"),("Akeem","Dixon","libero.dui.nec@quam.org","QYJ32LYI8EM"),("Ariel","Huffman","pretium.neque@Donecest.edu","UBZ17UAR6ND"),("Hyatt","Mckenzie","orci.luctus.et@utcursusluctus.co.uk","MSV86OLE9ZM"),("Sade","Sanders","tellus.Nunc@Vestibulum.net","NRD59TTL0PD");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Vance","Armstrong","mauris.rhoncus@rutrum.ca","ELS61THW5KF"),("Brandon","Black","Donec.non.justo@Nullamut.edu","JDN74CQC0PH"),("Inez","Jarvis","eget.mollis.lectus@auctornunc.com","QTT73VZG5CB"),("Luke","Gould","elementum.purus@leo.ca","JUY92AYJ8NU"),("Cleo","Patrick","accumsan.laoreet@atortor.com","DXD46FEP7XA"),("Ulysses","Foster","magna.Praesent@Sedeueros.com","EKC81SUR8NQ"),("Wayne","Doyle","Aliquam@euaccumsansed.ca","JFI71XKU9BR"),("Angelica","Frye","amet.luctus@loremipsumsodales.net","FFQ88CVU7YE"),("Nyssa","Foster","sagittis@Aliquamultrices.org","ZUF89DHX6CS"),("Beau","Aguilar","et.risus@Integer.co.uk","SHI80KQF9RC");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Francesca","Foley","convallis.convallis.dolor@purus.ca","QFZ86CBN4IA"),("Kelsie","Hansen","egestas@sagittis.net","MLI50UVB4MN"),("Cleo","Dale","varius.et@primisin.org","QXC31ZCD9NO"),("Jana","Leblanc","ligula.eu.enim@convallisdolorQuisque.co.uk","KMA21LWJ0EV"),("Hector","Mullins","luctus.et@semegetmassa.ca","WKH14NPU6AH"),("Kuame","Pearson","dignissim.tempor@perconubianostra.net","NPK51XNN5EY"),("Britanni","Burgess","mattis.Cras.eget@Phasellus.org","KOD99OGW5LG"),("Luke","Jones","lacus@etmagna.com","KMZ97NOA8MV"),("Kelly","Burris","Cras.dolor.dolor@litoratorquentper.net","OEF91XIH0UP"),("Shana","Nixon","nec@Nuncpulvinar.org","JKS66HQZ9OV");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Ocean","Stokes","arcu@Nuncut.ca","KXP33KJG1OU"),("Bo","Acevedo","vitae@urnaUttincidunt.net","EKQ22LYA6ZI"),("Hunter","Wyatt","nec@sedsapienNunc.org","KXC33VAD3PA"),("Jesse","Ayala","elit.Aliquam.auctor@nislNulla.org","HJT18OFT5AK"),("Russell","Hamilton","pharetra.sed.hendrerit@InloremDonec.edu","GQX27SYR6QV"),("Teagan","Chase","risus@doloregestasrhoncus.ca","BMG73LZC5FB"),("Lana","Charles","eget.volutpat@dignissim.edu","JLO14UZR6SC"),("Ezekiel","Nash","Ut.sagittis.lobortis@sedestNunc.com","PTY68UKH1DC"),("Troy","Whitfield","eros.Proin@ultriciesornareelit.com","COH90DAB2UH"),("Acton","Johnson","lectus@consectetuereuismod.org","LAK57SVD6DE");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Slade","Dejesus","mi.lacinia.mattis@a.edu","EAJ70EWR2XR"),("Simone","Hughes","tristique@Pellentesqueutipsum.ca","HWF54YFT7BC"),("Armand","Bullock","vel@Cras.net","FCU66OQG4YT"),("Amaya","Guthrie","eget.odio.Aliquam@Sedeueros.net","QNH29PHA1ZQ"),("Conan","Mcbride","eget@vulputate.com","FNL25EJS8AK"),("Herrod","Willis","vel@porttitortellusnon.net","RDW77TFB7LH"),("Brynne","Petty","ipsum.primis.in@nostra.edu","RLH42GJW0JS"),("Brett","Leblanc","Nullam@penatibus.net","JEZ39OEC3EM"),("Brenden","Barr","adipiscing@iaculislacus.ca","GCE06JMY7TD"),("Haley","Weber","velit.eget.laoreet@Proin.net","DEJ63LMI9YD");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Hilel","Donaldson","varius@ametmetus.net","LAR74BUS4KE"),("Cherokee","Tate","nulla@ultriciesligula.org","OLI65XTF2DE"),("Xena","Miller","a.purus@eu.ca","BHZ72RFG0QH"),("Quail","Terry","malesuada.fames.ac@Utnecurna.ca","BYZ00UKY7DR"),("David","Sampson","ullamcorper.Duis.cursus@sedpedenec.org","GJV14IJM2CJ"),("Galena","Hutchinson","cursus.Nunc@acsemut.com","FYI25QPI5LB"),("Ivy","Neal","Aliquam.auctor@urnaconvalliserat.edu","WRM42UFU1TX"),("Lana","Moody","Suspendisse.sed@risusNulla.com","QEW06JCB0XZ"),("Mikayla","Blair","nisi@eleifendCras.org","JHF16UPH1WE"),("Shelly","Holt","sed.libero.Proin@aliquamarcu.org","WYX10EIS7UY");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Jasper","Harper","dui@aarcu.edu","OSJ49CJE5DS"),("Tallulah","Woodard","Suspendisse.eleifend@mus.com","ZKI42VAL9CX"),("Nyssa","Daniel","mi@Donec.ca","IYR10LFW4MJ"),("Carter","Parrish","cursus@turpis.co.uk","KTO14YQY0NP"),("Jana","Craig","In.nec.orci@sapienmolestieorci.edu","SPJ27RCT8ZT"),("Quintessa","Wilcox","ornare@egestas.net","HNF99MSB5TC"),("Sade","Kline","egestas@pedesagittisaugue.org","ISV36GWS7VB"),("Brett","Orr","Sed.et@consequatpurus.co.uk","JRL49KHV0YQ"),("Dillon","Dickson","Aliquam.erat@auguescelerisquemollis.com","ZZC73WPH2ZG"),("Chester","Avila","felis.ullamcorper@ultrices.org","IKN02VSF8AA");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Justina","Pennington","urna.et.arcu@dignissim.org","GFR50YMO7QT"),("Thor","Fischer","dignissim@purus.edu","PJS33DBW9XW"),("Hunter","Underwood","consectetuer.rhoncus.Nullam@variuset.com","TMX96IRF4ND"),("Nerea","Manning","Mauris.blandit.enim@convallisest.com","LLU29PMV4OS"),("Felicia","Pearson","Praesent.interdum@laciniamattis.edu","RBF38THA1XV"),("Alice","Gregory","venenatis@Nuncacsem.net","BCI08LPY0NL"),("Noah","Bruce","velit.Cras@velit.com","SMH37WTK0GK"),("Wing","Horton","viverra.Maecenas@laoreet.co.uk","CSY24VHA9JK"),("Ashton","Yates","euismod@Suspendisse.edu","EOV38GDY4FY"),("Willow","Sharpe","Aenean@acsem.edu","YVF63JTE8UG");
INSERT INTO `usuarios` (`nombre`,`apellido`,`email`,`password`) VALUES ("Grant","Macdonald","ac.mattis.velit@dolortempusnon.co.uk","HTD95STN4AZ"),("Maxwell","Williams","neque@loremut.com","QGV95LRM6TV"),("Nadine","Acevedo","semper@ipsumnon.edu","YAX97HCK2ST"),("Margaret","Mayer","Curae.Phasellus@justonec.ca","MLG30XOB0ZY"),("Zeus","Barry","egestas.Fusce@mollis.ca","MZX45MWE0LO"),("Dale","Carrillo","lacinia.Sed@sapienCrasdolor.ca","DWB31WXL8KI"),("Ashton","Walter","Suspendisse@ut.co.uk","WIL15HGN1TK"),("Yael","Beck","Aenean.gravida@vitaealiquam.com","INQ07LYL1CJ"),("Jordan","Burton","eu.turpis.Nulla@orciDonec.com","LGK81PHS9ZQ"),("Bruno","Armstrong","nulla@ultricesaauctor.ca","WQO62IJA1XO");

select * from usuarios limit 10;

show variables where variable_name in ("hostname", "port"); 

#soluciona error de zona horaria
SET GLOBAL time_zone = '-3:00';


SELECT * FROM usuarios WHERE id_usuarios = 5;

update usuarios set email = "nuevo@a.com" where id_usuarios = 1;

SELECT * FROM usuarios WHERE id_usuarios > 90;
#comentarios
insert into productos (nombre, precio) values
("teclado", 200), ("mouse", 300), ("microfono", 500), ("parlantes", 200), 
("gabinete", 300), ("monitor", 500), ("procesador", 1000);

select * from usuarios;

delete from productos where id_producto > 7;

Select now();